Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,7 +24,7 @@ jobs:
     - name: Push image to docker hub Container Registry
       run: |
         docker push $REPO_NAME/$IMAGE_NAME
-        
+
     - name: run docker
       run: |
         docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
@@ -46,25 +46,25 @@ jobs:
         collection: postman/collection.json
         environment: postman/environment.json
         reporters: cli
-        bail: true
+        iteration: 3
 
-    - name: Check if we failed
-      id: fail-check
-      shell: bash
-      env:
-        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
-      run: |
-        printf '%s\n' "$JSON_DOC" > summary.json
-        cat summary.json
-        if grep -q Collection summary.json; then
-          echo "failed=false" >> $GITHUB_OUTPUT;
-        else
-          echo "failed=true" >> $GITHUB_OUTPUT;
-        fi
-
-    - name: fail if empty
-      if: ${{ steps.fail-check.outputs.failed == 'true' }}
-      run: exit 1
+#    - name: Check if we failed
+#      id: fail-check
+#      shell: bash
+#      env:
+#        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
+#      run: |
+#        printf '%s\n' "$JSON_DOC" > summary.json
+#        cat summary.json
+#        if grep -q Collection summary.json; then
+#          echo "failed=false" >> $GITHUB_OUTPUT;
+#        else
+#          echo "failed=true" >> $GITHUB_OUTPUT;
+#        fi
+#
+#    - name: fail if empty
+#      if: ${{ steps.fail-check.outputs.failed == 'true' }}
+#      run: exit 1
 
 
     - name: Output summary to console
